apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingressRestName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Values.hostName }}
    secretName: {{ .Values.secretName }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: {{ .Values.restServicePort }}
        path: /swagger